name: Go CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: Install dependencies
        run: go install
        working-directory: ${{ env.relativePath }}
      - name: Build SDK project
        run: go build
        working-directory: ${{ env.relativePath }}
      - name: Run unit tests
        run: go test
        working-directory: ${{ env.relativePath }}
